### ISSUE TITLE
Segmentation Fault due to access invalid seat

### ISSUE THREAD

**Issue by watasuke102** [zigen-project/zen#167]
If exiting zen when some view is focused, caused Segmentation Fault like following:

```
0x000055555555f717 in zn_scene_set_focused_view (self=0x555555d83ea0, view=0x0) at ../zen/scene/scene.c:78
78        struct wlr_seat* seat = server->input_manager->seat->wlr_seat;
#0  0x000055555555f717 in zn_scene_set_focused_view (self=0x555555d83ea0, view=0x0) at ../zen/scene/scene.c:78
#1  0x00005555555609a8 in wl_signal_emit (data=0x0, signal=0x555555f4dde8) at /usr/include/wayland-server-core.h:484
#2  zn_view_unmap (self=self@entry=0x555555f4dda0) at ../zen/scene/view.c:165
#3  0x000055555555dadc in zn_xdg_toplevel_view_handle_unmap (listener=0x555555f4de30, data=<optimized out>) at ../zen/xdg-toplevel-view.c:81
#4  0x00007ffff7d6ec14 in wlr_signal_emit_safe (signal=0x5555555a4eb8, data=0x5555555a4db0) at ../subprojects/wlroots/util/signal.c:29
#5  0x00007ffff7d3cf01 in unmap_xdg_surface (surface=0x5555555a4db0) at ../subprojects/wlroots/types/xdg_shell/wlr_xdg_surface.c:40
#6  0x00007ffff7d3dcc4 in reset_xdg_surface (xdg_surface=0x5555555a4db0) at ../subprojects/wlroots/types/xdg_shell/wlr_xdg_surface.c:426
#7  0x00007ffff7d3de12 in destroy_xdg_surface (surface=0x5555555a4db0) at ../subprojects/wlroots/types/xdg_shell/wlr_xdg_surface.c:464
#8  0x00007ffff7d3d9e8 in xdg_surface_handle_surface_destroy (listener=0x5555555a4e48, data=0x555555f4ce80) at ../subprojects/wlroots/types/xdg_shell/wlr_xdg_surface.c:361
#9  0x00007ffff7d6ec14 in wlr_signal_emit_safe (signal=0x555555f4d150, data=0x555555f4ce80) at ../subprojects/wlroots/util/signal.c:29
#10 0x00007ffff7d6002f in surface_handle_resource_destroy (resource=0x55555610c7a0) at ../subprojects/wlroots/types/wlr_surface.c:702
#11 0x00007ffff7dcd8ba in  () at /usr/lib/libwayland-server.so.0
#12 0x00007ffff7dcf689 in wl_resource_destroy () at /usr/lib/libwayland-server.so.0
#13 0x00007ffff7d6017d in surface_handle_renderer_destroy (listener=0x555555f4d188, data=0x5555556a6cc0) at ../subprojects/wlroots/types/wlr_surface.c:728
#14 0x00007ffff7d6ec14 in wlr_signal_emit_safe (signal=0x5555556a6cd0, data=0x5555556a6cc0) at ../subprojects/wlroots/util/signal.c:29
#15 0x00007ffff7cf8495 in wlr_renderer_destroy (r=0x5555556a6cc0) at ../subprojects/wlroots/render/wlr_renderer.c:54
#16 0x000055555555d69c in zn_server_destroy (self=0x55555559d1b0) at ../zen/server.c:346
#17 0x000055555555acdf in main (argc=<optimized out>, argv=<optimized out>) at ../zen/main.c:197
```

**Comment by watasuke102** [comment]
solved by #168
